#!/bin/sh /etc/rc.common
# Copyright (C) 2006 OpenWrt.org

START=21

PATH_TO_SCRIPT="/root/webserver"
SCRIPT="server.py"

boot() {
	start "$@"
}

start() {
	/usr/bin/python3 "${PATH_TO_SCRIPT}${SCRIPT}" &
}

stop() {
	SEARCH_PATTERN="[p]ython3 ${PATH_TO_SCRIPT}${SCRIPT}"
	pid=`ps | grep "$SEARCH_PATTERN" | awk '{print $1}'`
	kill $pid
}

